name: enough_mail
description: IMAP, POP3 and SMTP for email developers. Choose between a low
  level and a high level API for mailing. Parse and generate MIME messages.
  Discover email settings.
version: 2.1.6
homepage: https://github.com/Enough-Software/enough_mail

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  basic_utils: ^5.0.0
  collection: ^1.16.0
  crypto: ^3.0.0
  encrypt: ^5.0.0
  enough_convert: ^1.5.0
  event_bus: ^2.0.0
  intl: ^0.19.0
  json_annotation: ^4.8.0
  pointycastle: ^3.6.0
  synchronized: ^3.1.0
  xml: ">=6.0.0 <7.0.0"

dev_dependencies:
  build_runner: ^2.3.0
  json_serializable: ^6.3.0
  lints: ^3.0.0
  test: ^1.20.1
  timezone: ^0.9.0
